-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2022-04-27 12:23:47 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

--Group: 69
--student name: Sihao Chen; Jiawei Ren, Nikita Bhararia 
-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL wc_schema.txt

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE commentary_language CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE participant CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE port_temperature CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE tour_available CASCADE CONSTRAINTS;

DROP TABLE trip CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cabin (
    cabin_number    VARCHAR2(3) NOT NULL,
    cabin_capacity  NUMBER(2) NOT NULL,
    cabin_class     CHAR(2) NOT NULL,
    ship_id         NUMBER(10) NOT NULL
);

ALTER TABLE cabin
    ADD CONSTRAINT chk_cabinclass CHECK ( cabin_class IN ( 'B', 'I', 'O', 'S' ) );

COMMENT ON COLUMN cabin.cabin_number IS
    'cabins on a given ship are identified by a cabin number';

COMMENT ON COLUMN cabin.cabin_capacity IS
    'e capacity of a particular cabin';

COMMENT ON COLUMN cabin.cabin_class IS
    'e class of the cabin';

COMMENT ON COLUMN cabin.ship_id IS
    'a ship code to identify the ship';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_number,
                                                        ship_id );

CREATE TABLE commentary_language (
    tour_no        NUMBER(2) NOT NULL,
    port_code      VARCHAR2(7) NOT NULL,
    language_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN commentary_language.tour_no IS
    'a tour number';

COMMENT ON COLUMN commentary_language.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN commentary_language.language_name IS
    'commentary language';

ALTER TABLE commentary_language
    ADD CONSTRAINT commentary_language_pk PRIMARY KEY ( tour_no,
                                                        port_code,
                                                        language_name );

CREATE TABLE country (
    ctry_code  VARCHAR2(15) NOT NULL,
    ctry_name  VARCHAR2(7) NOT NULL
);

COMMENT ON COLUMN country.ctry_code IS
    'ISO country code';

COMMENT ON COLUMN country.ctry_name IS
    'name of country';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( ctry_code );

CREATE TABLE cruise (
    cruise_id     NUMBER(4) NOT NULL,
    cruise_name   VARCHAR2(20) NOT NULL,
    cruise_descp  VARCHAR2(200) NOT NULL,
    ship_id       NUMBER(10) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'cruise is identified by a cruise id';

COMMENT ON COLUMN cruise.cruise_name IS
    'cruise name';

COMMENT ON COLUMN cruise.cruise_descp IS
    'cruise description ';

COMMENT ON COLUMN cruise.ship_id IS
    'a ship code to identify the ship';

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE manifest (
    cabin_number  VARCHAR2(3) NOT NULL,
    ship_id       NUMBER(10) NOT NULL,
    cruise_id     NUMBER(4) NOT NULL,
    pax_id        NUMBER(5) NOT NULL,
    pax_board_dt  DATE NOT NULL
);

COMMENT ON COLUMN manifest.cabin_number IS
    'cabins on a given ship are identified by a cabin number';

COMMENT ON COLUMN manifest.ship_id IS
    'a ship code to identify the ship';

COMMENT ON COLUMN manifest.cruise_id IS
    'cruise is identified by a cruise id';

COMMENT ON COLUMN manifest.pax_id IS
    'passenger is assigned a unique id';

COMMENT ON COLUMN manifest.pax_board_dt IS
    'date and time when they first boarded the ship.';

ALTER TABLE manifest
    ADD CONSTRAINT manifest_pk PRIMARY KEY ( cabin_number,
                                             ship_id,
                                             cruise_id,
                                             pax_id );

CREATE TABLE operator (
    operator_id       NUMBER(10) NOT NULL,
    operator_name     VARCHAR2(30) NOT NULL,
    operator_officer  VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN operator.operator_id IS
    'company''s id';

COMMENT ON COLUMN operator.operator_name IS
    'company''s name';

COMMENT ON COLUMN operator.operator_officer IS
    'company''s CEO';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( operator_id );

CREATE TABLE participant (
    pa_id       NUMBER(4) NOT NULL,
    pax_id      NUMBER(5) NOT NULL,
    cruise_id   NUMBER(4) NOT NULL,
    tour_no     NUMBER(2) NOT NULL,
    port_code   VARCHAR2(7) NOT NULL,
    tour_date   DATE NOT NULL,
    pa_payment  VARCHAR2(3) NOT NULL
);

ALTER TABLE participant
    ADD CONSTRAINT ck_payment CHECK ( pa_payment IN ( 'NO', 'YES' ) );

COMMENT ON COLUMN participant.pa_id IS
    'id for participants';

COMMENT ON COLUMN participant.pax_id IS
    'passenger is assigned a unique id';

COMMENT ON COLUMN participant.cruise_id IS
    'cruise is identified by a cruise id';

COMMENT ON COLUMN participant.tour_no IS
    'a tour number';

COMMENT ON COLUMN participant.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN participant.tour_date IS
    'date of tour';

COMMENT ON COLUMN participant.pa_payment IS
    'received or not received';

ALTER TABLE participant ADD CONSTRAINT participant_pk PRIMARY KEY ( pa_id );

ALTER TABLE participant
    ADD CONSTRAINT participant_nk UNIQUE ( pax_id,
                                           tour_no,
                                           port_code,
                                           tour_date,
                                           cruise_id );

CREATE TABLE passenger (
    pax_id            NUMBER(5) NOT NULL,
    pax_fname         VARCHAR2(10) NOT NULL,
    pax_lname         VARCHAR2(10) NOT NULL,
    pax_dob           DATE NOT NULL,
    pax_gender        VARCHAR2(10) NOT NULL,
    pax_street        VARCHAR2(20) NOT NULL,
    pax_town          VARCHAR2(10) NOT NULL,
    pax_postcode      VARCHAR2(10) NOT NULL,
    pax_ctry          VARCHAR2(10) NOT NULL,
    pax_language      VARCHAR2(20) NOT NULL,
    pax_phone         CHAR(10),
    ctry_code         VARCHAR2(15) NOT NULL,
    passenger_pax_id  NUMBER(5)
);

COMMENT ON COLUMN passenger.pax_id IS
    'passenger is assigned a unique id';

COMMENT ON COLUMN passenger.pax_fname IS
    ' passenger''s fist name';

COMMENT ON COLUMN passenger.pax_lname IS
    ' passenger''s last name';

COMMENT ON COLUMN passenger.pax_dob IS
    ' date of birth';

COMMENT ON COLUMN passenger.pax_gender IS
    'passenger''s gender';

COMMENT ON COLUMN passenger.pax_street IS
    'street (including street number),';

COMMENT ON COLUMN passenger.pax_town IS
    'name of town';

COMMENT ON COLUMN passenger.pax_postcode IS
    'postcode';

COMMENT ON COLUMN passenger.pax_ctry IS
    'country';

COMMENT ON COLUMN passenger.pax_language IS
    'speaking language';

COMMENT ON COLUMN passenger.pax_phone IS
    'phone number';

COMMENT ON COLUMN passenger.ctry_code IS
    'ISO country code';

COMMENT ON COLUMN passenger.passenger_pax_id IS
    'passenger is assigned a unique id';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( pax_id );

CREATE TABLE port (
    port_code        VARCHAR2(7) NOT NULL,
    port_name        VARCHAR2(10) NOT NULL,
    port_ctry        VARCHAR2(10) NOT NULL,
    port_population  NUMBER(7) NOT NULL,
    port_longitude   NUMBER(9, 7) NOT NULL,
    port_latitude    NUMBER(9, 7) NOT NULL,
    ctry_code        VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN port.port_name IS
    'port''s name,
';

COMMENT ON COLUMN port.port_ctry IS
    'country the port is in';

COMMENT ON COLUMN port.port_population IS
    ' port population';

COMMENT ON COLUMN port.port_longitude IS
    'longitude';

COMMENT ON COLUMN port.port_latitude IS
    'latitude';

COMMENT ON COLUMN port.ctry_code IS
    'ISO country code';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE port_temperature (
    port_code           VARCHAR2(7) NOT NULL,
    port_temp_mth       CHAR(3) NOT NULL,
    port_temp_avg_high  NUMBER(2) NOT NULL,
    port_temp_avg_low   NUMBER(2) NOT NULL
);

COMMENT ON COLUMN port_temperature.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN port_temperature.port_temp_mth IS
    'month recorded';

COMMENT ON COLUMN port_temperature.port_temp_avg_high IS
    'average highest temperature';

COMMENT ON COLUMN port_temperature.port_temp_avg_low IS
    'average lowest temperature';

ALTER TABLE port_temperature ADD CONSTRAINT port_temperature_pk PRIMARY KEY ( port_code,
                                                                              port_temp_mth );

CREATE TABLE ship (
    ship_id                 NUMBER(10) NOT NULL,
    ship_name               VARCHAR2(30) NOT NULL,
    ship_commissioned_date  DATE NOT NULL,
    ship_tonnage            NUMBER(5) NOT NULL,
    ship_max_guest          NUMBER(4) NOT NULL,
    ship_reg_country        VARCHAR2(10) NOT NULL,
    ctry_code               VARCHAR2(15) NOT NULL,
    operator_id             NUMBER(10) NOT NULL
);

COMMENT ON COLUMN ship.ship_id IS
    'a ship code to identify the ship';

COMMENT ON COLUMN ship.ship_name IS
    'ship''s name';

COMMENT ON COLUMN ship.ship_commissioned_date IS
    'e date the ship was commissioned';

COMMENT ON COLUMN ship.ship_tonnage IS
    'ship''s tonnage,';

COMMENT ON COLUMN ship.ship_max_guest IS
    's maximum guest capacity';

COMMENT ON COLUMN ship.ship_reg_country IS
    'e name of the country in which the ship is registered.';

COMMENT ON COLUMN ship.ctry_code IS
    'ISO country code';

COMMENT ON COLUMN ship.operator_id IS
    'company''s id';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_id );

CREATE TABLE tour (
    tour_no    NUMBER(2) NOT NULL,
    port_code  VARCHAR2(7) NOT NULL,
    tour_date  DATE NOT NULL
);

COMMENT ON COLUMN tour.tour_no IS
    'a tour number';

COMMENT ON COLUMN tour.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN tour.tour_date IS
    'date of tour';

ALTER TABLE tour
    ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_no,
                                         port_code,
                                         tour_date );

CREATE TABLE tour_available (
    tour_no                 NUMBER(2) NOT NULL,
    port_code               VARCHAR2(7) NOT NULL,
    tour_mini_participants  NUMBER(3) NOT NULL,
    tour_name               VARCHAR2(10) NOT NULL,
    tour_desc               VARCHAR2(200) NOT NULL,
    tour_hours              NUMBER(2, 1) NOT NULL,
    tour_cost               NUMBER(3) NOT NULL,
    tour_wheel_chair        VARCHAR2(3) NOT NULL,
    tour_availablility      VARCHAR2(10) NOT NULL,
    tour_start_time         VARCHAR2(5) NOT NULL
);

ALTER TABLE tour_available
    ADD CONSTRAINT ck_participant CHECK ( tour_mini_participants BETWEEN 11 AND 100 );

ALTER TABLE tour_available
    ADD CONSTRAINT yes_no CHECK ( tour_wheel_chair IN ( 'NO', 'YES' ) );

ALTER TABLE tour_available
    ADD CONSTRAINT intervals CHECK ( tour_availablility IN ( 'Daily', 'Friday', 'Monday',
    'Saturday', 'Sunday',
                                                             'Thursday',
                                                             'Tuesday',
                                                             'Wednesday',
                                                             'Weekdays' ) );

COMMENT ON COLUMN tour_available.tour_no IS
    'a tour number';

COMMENT ON COLUMN tour_available.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN tour_available.tour_mini_participants IS
    'minimum participant';

COMMENT ON COLUMN tour_available.tour_name IS
    'name of tour';

COMMENT ON COLUMN tour_available.tour_desc IS
    'description of tour';

COMMENT ON COLUMN tour_available.tour_hours IS
    'how many hours ';

COMMENT ON COLUMN tour_available.tour_cost IS
    'money';

COMMENT ON COLUMN tour_available.tour_wheel_chair IS
    'yes or no';

COMMENT ON COLUMN tour_available.tour_availablility IS
    'availabe interval';

COMMENT ON COLUMN tour_available.tour_start_time IS
    'start time of tour';

ALTER TABLE tour_available ADD CONSTRAINT tour_available_pk PRIMARY KEY ( tour_no,
                                                                          port_code );

CREATE TABLE trip (
    cruise_id    NUMBER(4) NOT NULL,
    port_code    VARCHAR2(7) NOT NULL,
    trip_arr_dt  DATE NOT NULL,
    trip_dep_dt  DATE NOT NULL
);

COMMENT ON COLUMN trip.cruise_id IS
    'cruise is identified by a cruise id';

COMMENT ON COLUMN trip.port_code IS
    ' port code recorded to identify the port';

COMMENT ON COLUMN trip.trip_arr_dt IS
    'arrival times for a given cruise.';

COMMENT ON COLUMN trip.trip_dep_dt IS
    'departure times for a given cruise.';

ALTER TABLE trip ADD CONSTRAINT trip_pk PRIMARY KEY ( cruise_id,
                                                      port_code );

ALTER TABLE manifest
    ADD CONSTRAINT cabin_manifest FOREIGN KEY ( cabin_number,
                                                ship_id )
        REFERENCES cabin ( cabin_number,
                           ship_id );

ALTER TABLE passenger
    ADD CONSTRAINT country_passenger FOREIGN KEY ( ctry_code )
        REFERENCES country ( ctry_code );

ALTER TABLE port
    ADD CONSTRAINT country_port FOREIGN KEY ( ctry_code )
        REFERENCES country ( ctry_code );

ALTER TABLE ship
    ADD CONSTRAINT country_ship FOREIGN KEY ( ctry_code )
        REFERENCES country ( ctry_code );

ALTER TABLE manifest
    ADD CONSTRAINT cruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE participant
    ADD CONSTRAINT cruise_participant FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE tour
    ADD CONSTRAINT exact_tour FOREIGN KEY ( tour_no,
                                            port_code )
        REFERENCES tour_available ( tour_no,
                                    port_code );

ALTER TABLE passenger
    ADD CONSTRAINT guardian FOREIGN KEY ( passenger_pax_id )
        REFERENCES passenger ( pax_id );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( operator_id )
        REFERENCES operator ( operator_id );

ALTER TABLE manifest
    ADD CONSTRAINT passenger_manifest FOREIGN KEY ( pax_id )
        REFERENCES passenger ( pax_id );

ALTER TABLE participant
    ADD CONSTRAINT passenger_participant FOREIGN KEY ( pax_id )
        REFERENCES passenger ( pax_id );

ALTER TABLE trip
    ADD CONSTRAINT port_cruise FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE port_temperature
    ADD CONSTRAINT port_temperature FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE tour_available
    ADD CONSTRAINT port_tour_availabe FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE trip
    ADD CONSTRAINT port_trip FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_id )
        REFERENCES ship ( ship_id );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_id )
        REFERENCES ship ( ship_id );

ALTER TABLE commentary_language
    ADD CONSTRAINT tour_language FOREIGN KEY ( tour_no,
                                               port_code )
        REFERENCES tour_available ( tour_no,
                                    port_code );

ALTER TABLE participant
    ADD CONSTRAINT tour_participant FOREIGN KEY ( tour_no,
                                                  port_code,
                                                  tour_date )
        REFERENCES tour ( tour_no,
                          port_code,
                          tour_date );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
SPOOL off
set echo off